Update avbtool version and adjust clone branch

diff --git a/.github/workflows/n.yml b/.github/workflows/n.yml
--- a/.github/workflows/n.yml
+++ b/.github/workflows/n.yml
@@ -129,7 +129,7 @@ jobs:
           fec --version || fec --help || true
 
       - name: Clone avbtool 1.1.0 from AOSP android-9.0.0_r34
-        run: git clone --depth 1 --branch android-9.0.0_r34 https://android.googlesource.com/platform/external/avb
+        run: git clone --depth 1 --branch android-10.0.0_r47 https://android.googlesource.com/platform/external/avb
 
       - name: Download zip
         run: wget -O h.zip https://github.com/coara-chocomaru/monooki/releases/download/%E3%81%A6%E3%81%99%E3%81%A899/h.zip
@@ -345,6 +345,7 @@ jobs:
             --algorithm SHA256_RSA4096 \
             --rollback_index 0 \
             --flags 0 \
+            --rollback_index_location 0 \
             --chain_partition vbmeta_system:2:keys/vbmeta_system.avbpubkey \
             --prop com.android.build.vendor.fingerprint:Rakuten/P780/P780:11/RKQ1.210715.001/264:user/release-keys \
             --prop com.android.build.vendor.os_version:11 \
@@ -363,6 +364,102 @@ jobs:
             --include_descriptors_from_image signed/vendor_boot.img \
             --include_descriptors_from_image signed/odm.img \
             --include_descriptors_from_image signed/vendor.img
+
+      - name: Assert final vbmeta matches stock structure exactly
+        run: |
+          cd $GITHUB_WORKSPACE
+          python avb/avbtool info_image --image signed/vbmeta.img > /tmp/actual_vbmeta_info.log
+
+          cat > /tmp/stock_vbmeta_info.log << 'STOCK_VBMETA_EOF'
+          Minimum libavb version:   1.0
+          Header Block:             256 bytes
+          Authentication Block:     576 bytes
+          Auxiliary Block:          3968 bytes
+          Public key (sha1):        2597c218aae470a130f61162feaae70afd97f011
+          Algorithm:                SHA256_RSA4096
+          Rollback Index:           0
+          Flags:                    0
+          Rollback Index Location:  0
+          Release String:           'avbtool 1.1.0'
+          Descriptors:
+              Chain Partition descriptor:
+                Partition Name:          vbmeta_system
+                Rollback Index Location: 2
+                Public key (sha1):       cdbb77177f731920bbe0a0f94f84d9038ae0617d
+              Prop: com.android.build.vendor.fingerprint -> 'Rakuten/P780/P780:11/RKQ1.210715.001/264:user/release-keys'
+              Prop: com.android.build.vendor.os_version -> '11'
+              Prop: com.android.build.vendor.security_patch -> '2024-02-01'
+              Prop: com.android.build.vendor.security_patch -> '2024-02-01'
+              Prop: com.android.build.vendor_boot.fingerprint -> 'Rakuten/P780/P780:11/RKQ1.210715.001/264:user/release-keys'
+              Prop: com.android.build.boot.fingerprint -> 'Rakuten/P780/P780:11/RKQ1.210715.001/264:user/release-keys'
+              Prop: com.android.build.boot.os_version -> '11'
+              Prop: com.android.build.boot.security_patch -> '2024-02-01'
+              Prop: com.android.build.boot.security_patch -> '2024-02-01'
+              Prop: com.android.build.odm.fingerprint -> 'Rakuten/P780/P780:11/RKQ1.210715.001/264:user/release-keys'
+              Prop: com.android.build.odm.os_version -> '11'
+              Prop: com.android.build.dtbo.fingerprint -> 'Rakuten/P780/P780:11/RKQ1.210715.001/264:user/release-keys'
+              Hash descriptor:
+                Image Size:            __BOOT_IMAGE_SIZE__ bytes
+                Hash Algorithm:        sha256
+                Partition Name:        boot
+                Salt:                  e5221de4db25a10ca4ce5f651de5498c423ac4f86dff69815f3fcf5a9f370bde
+                Digest:                __BOOT_DIGEST__
+                Flags:                 0
+              Hash descriptor:
+                Image Size:            3296351 bytes
+                Hash Algorithm:        sha256
+                Partition Name:        dtbo
+                Salt:                  20e6fe8fc5b31ea3bcafdfea79854073b98e01a9c451b9046ebb6c4c12754a29
+                Digest:                2f67be55bdae9a13455b95efba1d0adc1e8e27051daabdef04ce35f8e79102d8
+                Flags:                 0
+              Hash descriptor:
+                Image Size:            1359872 bytes
+                Hash Algorithm:        sha256
+                Partition Name:        vendor_boot
+                Salt:                  daef981c72271938f8c21c865d2b1f6e09eac002364f463986cd0fa5fc180d8d
+                Digest:                9a0e8906928dd1ab033f2ea81ea926833fe946bc6a0467106721e54252c12ba4
+                Flags:                 0
+              Hashtree descriptor:
+                Version of dm-verity:  1
+                Image Size:            1048576 bytes
+                Tree Offset:           1048576
+                Tree Size:             12288 bytes
+                Data Block Size:       4096 bytes
+                Hash Block Size:       4096 bytes
+                FEC num roots:         2
+                FEC offset:            1060864
+                FEC size:              16384 bytes
+                Hash Algorithm:        sha1
+                Partition Name:        odm
+                Salt:                  b8055364fe0aeed890e478d3a486b15972da56cde14724fe4a84f9d6ea1d1195
+                Root Digest:           60e6406accd5aba9a5aa6e321428540b3d4845db
+                Flags:                 0
+              Hashtree descriptor:
+                Version of dm-verity:  1
+                Image Size:            770195456 bytes
+                Tree Offset:           770195456
+                Tree Size:             6074368 bytes
+                Data Block Size:       4096 bytes
+                Hash Block Size:       4096 bytes
+                FEC num roots:         2
+                FEC offset:            776269824
+                FEC size:              6144000 bytes
+                Hash Algorithm:        sha1
+                Partition Name:        vendor
+                Salt:                  b8055364fe0aeed890e478d3a486b15972da56cde14724fe4a84f9d6ea1d1195
+                Root Digest:           e5b31d90fe48f0ec62a58a7ec809f1911497ec64
+                Flags:                 0
+          STOCK_VBMETA_EOF
+
+          sed -i "s/__BOOT_IMAGE_SIZE__/${BOOT_EXPECTED_IMAGE_SIZE}/" /tmp/stock_vbmeta_info.log
+          sed -i "s/__BOOT_DIGEST__/${BOOT_EXPECTED_DIGEST}/" /tmp/stock_vbmeta_info.log
+
+          diff -u <(sed 's/[[:space:]]*$//' /tmp/stock_vbmeta_info.log) <(sed 's/[[:space:]]*$//' /tmp/actual_vbmeta_info.log)
+          if [ $? -ne 0 ]; then
+            echo "FAILED: signed/vbmeta.img does not match expected structure"
+            exit 1
+          fi
+          echo "OK: boot以外はstockと完全一致、bootのみ更新分の差分を正しく反映"
 
       - name: Show vbmeta info
         run: |
